version: '3.8'

services:
  mysql-master:
    image: mysql:latest
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - ./master/my.cnf:/etc/mysql/my.cnf
      - master-data:/var/lib/mysql
    networks:
      - mysql-network

  mysql-slave1:
    image: mysql:latest
    container_name: mysql-slave1
    depends_on:
      - mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"
    volumes:
      - ./slave1/my.cnf:/etc/mysql/my.cnf
      - slave1-data:/var/lib/mysql
    networks:
      - mysql-network

  mysql-slave2:
    image: mysql:latest
    container_name: mysql-slave2
    depends_on:
      - mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3308:3306"
    volumes:
      - ./slave2/my.cnf:/etc/mysql/my.cnf
      - slave2-data:/var/lib/mysql
    networks:
      - mysql-network
      
volumes:
  master-data:
  slave1-data:
  slave2-data:

networks:
  mysql-network:
    driver: bridge
