version: '3'

services:
  mysql-master:
    image: mysql:latest
    container_name: mysql-master
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - ./master-data:/var/lib/mysql
      - ./master-config:/etc/mysql/conf.d
    networks:
      - mysql-network

  mysql-slave1:
    image: mysql:latest
    container_name: mysql-slave1
    depends_on:
      - mysql-master
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"
    volumes:
      - ./slave1-data:/var/lib/mysql
      - ./slave-config:/etc/mysql/conf.d
    networks:
      - mysql-network

  mysql-slave2:
    image: mysql:latest
    container_name: mysql-slave2
    depends_on:
      - mysql-master
    command: --server-id=3 --log-bin=mysql-bin --binlog-format=row
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3308:3306"
    volumes:
      - ./slave2-data:/var/lib/mysql
      - ./slave-config:/etc/mysql/conf.d
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge